name: Build SimpleModDownloader

on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v2
    
    - name: update repo
      run: |
        git config --global --add safe.directory /__w/SimpleModDownloader/SimpleModDownloader/lib/borealis
        git config --global --add safe.directory /__w/SimpleModDownloader/SimpleModDownloader/lib/ini
        git config --global --add safe.directory /__w/SimpleModDownloader/SimpleModDownloader
        git submodule update --init --recursive
  
    - name: build SimpleModDownloader
      run: | 
        make
      
    - name: Set check status
      uses: actions/github-script@v4
      with:
        script: |
          const token = process.env.GITHUB_TOKEN;
          const octokit = github.getOctokit(token);
          octokit.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'Build Status',
            head_sha: context.sha,
            status: 'completed',
            conclusion: 'success',
            output: {
              title: 'Build Successful',
              summary: 'The project compiled successfully.'
            }
          });
      
    - uses: actions/upload-artifact@v2
      with:
        name: SimpleModDownloader
        path: SimpleModDownloader.nro
